#! /bin/bash

dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_filtered_experiments.json ../data/figure3/cspad_filtered_reflections.pickle tag=filtered
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step7_level2.json ../data/figure3/cspad_refined_reflections_step7_level2.pickle tag=refinedstep7_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/v3_refine/cspad_refined_experiments_step7_level2.json ../data/figure3/v3_refine/cspad_refined_reflections_step7_level2.pickle tag=refinedstep7_level2_v3_refine
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/v4_refine/cspad_refined_experiments_step7_level2.json ../data/figure3/v4_refine/cspad_refined_reflections_step7_level2.pickle tag=refinedstep7_level2_v4_refine
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/v5_refine/cspad_refined_experiments_step7_level2.json ../data/figure3/v5_refine/cspad_refined_reflections_step7_level2.pickle tag=refinedstep7_level2_v5_refine
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_filtered_experiments.json ../data/figure3/cspad_reflections_step0.pickle tag=pre_step0
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step0_level0.json ../data/figure3/cspad_refined_reflections_step0_level0.pickle tag=step0_level0
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step0_level1.json ../data/figure3/cspad_refined_reflections_step0_level1.pickle tag=step0_level1
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step0_level1.json ../data/figure3/inputs/pre_step1.pickle tag=pre_step1
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step1_level2.json ../data/figure3/cspad_refined_reflections_step1_level2.pickle tag=step1_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step1_level2.json ../data/figure3/inputs/pre_step2.pickle tag=pre_step2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step2_level2.json ../data/figure3/cspad_refined_reflections_step2_level2.pickle tag=step2_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step2_level2.json ../data/figure3/inputs/pre_step3.pickle tag=pre_step3
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step3_level2.json ../data/figure3/cspad_refined_reflections_step3_level2.pickle tag=step3_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step3_level2.json ../data/figure3/inputs/pre_step4.pickle tag=pre_step4
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step4_level2.json ../data/figure3/cspad_refined_reflections_step4_level2.pickle tag=step4_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step4_level2.json ../data/figure3/inputs/pre_step5.pickle tag=pre_step5
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step5_level2.json ../data/figure3/cspad_refined_reflections_step5_level2.pickle tag=step5_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step5_level2.json ../data/figure3/inputs/pre_step6.pickle tag=pre_step6
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step6_level2.json ../data/figure3/cspad_refined_reflections_step6_level2.pickle tag=step6_level2
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step6_level2.json ../data/figure3/inputs/pre_step7.pickle tag=pre_step7
dev.cctbx.xfel.detector_residuals  residuals.exclude_outliers_from_refinement=False residuals.plot_max=0.3 hierarchy_level=2 dot_size=1 colormap=YlGnBu_r panel_numbers=False plots.per_image_RMSDs_histogram=False plots.deltaXY_by_deltapsi=False plots.unit_cell_histograms=False plots.include_radial_and_transverse=False repredict_input_reflections=False verbose=False save_png=True ../data/figure3/cspad_refined_experiments_step7_level2.json ../data/figure3/cspad_refined_reflections_step7_level2.pickle tag=step7_level2

